language: ruby

rvm:
  - 2.4.0

addons:
  postgresql: "9.4"

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.travis.yml config/database.yml
  - nvm install 7.7
  - nvm use 7.7
  - npm install

script:
  - bundle exec rails spec
